import type { AdminAction, AdminMatchDetail, AdminSummary, AdminUserDetail, Page } from "./types";

export const fixtureUser: AdminUserDetail = {
  id: "11111111-1111-4111-8111-111111111111",
  username: "max",
  displayName: "Max",
  role: "USER",
  blocked: false,
  blockedAt: null,
  blockedReason: null,
  createdAt: "2026-10-01T12:00:00Z",
  updatedAt: "2026-10-04T12:00:00Z",
  matchCount: 28,
  ratings: [
    {
      gameMode: "standard",
      rating: 1800,
      rankTier: "BLACK_MOON",
      ratingDeviation: 50,
      volatility: 0.06,
      ratedGames: 24,
      updatedAt: "2026-10-04T12:00:00Z",
    },
    {
      gameMode: "draft",
      rating: 900,
      rankTier: "HALF",
      ratingDeviation: 70,
      volatility: 0.06,
      ratedGames: 11,
      updatedAt: "2026-10-04T12:00:00Z",
    },
    {
      gameMode: "classic",
      rating: 2050,
      rankTier: "DESTINY",
      ratingDeviation: 40,
      volatility: 0.06,
      ratedGames: 45,
      updatedAt: "2026-10-04T12:00:00Z",
    },
  ],
};
export const fixtureMatch: AdminMatchDetail = {
  matchId: "22222222-2222-4222-8222-222222222222",
  roomId: "night-games",
  lobbyName: "Night Games",
  status: "FINISHED",
  gameMode: "classic",
  origin: "MANUAL",
  matchType: "RATED",
  createdById: fixtureUser.id,
  createdAt: fixtureUser.createdAt,
  updatedAt: fixtureUser.updatedAt,
  startedAt: fixtureUser.createdAt,
  finishedAt: fixtureUser.updatedAt,
  finalRevision: 80,
  ratingProcessedAt: fixtureUser.updatedAt,
  result: {
    winnerUserId: fixtureUser.id,
    winnerSeat: "P1",
    loserUserId: null,
    loserSeat: "P2",
    finishReason: "allEnemyUnitsDefeated",
    durationMs: 240000,
    turnCount: 18,
  },
  participants: [
    {
      userId: fixtureUser.id,
      seat: "P1",
      displayName: "Max",
      username: "max",
      displayNameSnapshot: "Max",
      outcome: "WIN",
      identityType: "ACCOUNT",
    },
    {
      userId: null,
      seat: "P2",
      displayName: null,
      username: null,
      displayNameSnapshot: "Polina",
      outcome: "LOSS",
      identityType: "GUEST_OR_DELETED_ACCOUNT",
    },
  ],
  actionCount: 80,
  snapshotCount: 4,
  durableRevision: 80,
  latestActionRevision: 80,
  latestSnapshot: { revision: 80, formatVersion: 1, createdAt: fixtureUser.updatedAt },
};
export const fixtureSummary: AdminSummary = {
  users: { total: 1248, active: 1236, blocked: 12, byRole: { USER: 1242, MODERATOR: 4, ADMIN: 2 } },
  matches: {
    total: 2180,
    byStatus: { WAITING: 5, IN_PROGRESS: 12, FINISHED: 2159, CANCELLED: 4 },
    byGameMode: { standard: 1100, draft: 360, classic: 720 },
    classification: { CASUAL: 680, RATED: 1500 },
  },
  activity: { usersCreatedLast7d: 32, matchesCreatedLast24h: 84, matchesFinishedLast24h: 77 },
};
export const fixtureAction: AdminAction = {
  revision: 37,
  actorUserId: fixtureUser.id,
  actorSeat: "P1",
  actionType: "move",
  actionPayload: { type: "move", unitId: "knight", to: { x: 3, y: 4 } },
  payloadValid: true,
  formatVersion: 1,
  createdAt: fixtureUser.updatedAt,
};
export const fixturePage = <T>(items: T[], page = 1, total = items.length): Page<T> => ({
  items,
  pagination: { page, limit: 20, total, totalPages: Math.ceil(total / 20) },
});
