import { getUnitDefinition } from "../../units";
import {
  ABILITY_BERSERK_AUTO_DEFENSE,
  ABILITY_DUOLINGO_BERSERKER,
  ABILITY_DUOLINGO_PUSH_NOTIFICATION,
  ABILITY_DUOLINGO_SKIP_CLASSES,
  ABILITY_DUOLINGO_STRICK,
  ABILITY_FEMTO_DIVINE_MOVE,
  ABILITY_FEMTO_GOD_HP,
  ABILITY_FEMTO_MULTI_BERSERK_SPEAR,
  ABILITY_FRISK_CLEAN_SOUL,
  ABILITY_FRISK_GENOCIDE,
  ABILITY_FRISK_ONE_PATH,
  ABILITY_FRISK_PACIFISM,
  ABILITY_GENGHIS_KHAN_LEGEND_OF_THE_STEPPES,
  ABILITY_GRIFFITH_FEMTO_REBIRTH,
  ABILITY_GRIFFITH_WRETCHED_MAN,
  ABILITY_GUTS_ARBALET,
  ABILITY_GUTS_BERSERK_MODE,
  ABILITY_GUTS_CANNON,
  ABILITY_HASSAN_ASSASIN_ORDER,
  ABILITY_HASSAN_ONE_WITH_SAND,
  ABILITY_HASSAN_TRUE_ENEMY,
  ABILITY_JACK_RIPPER_DISMEMBERMENT,
  ABILITY_JACK_RIPPER_LEGEND_KILLER,
  ABILITY_JACK_RIPPER_SNARES,
  ABILITY_JACK_RIPPER_SURGERY,
  ABILITY_JEBE_DURABLE,
  ABILITY_JEBE_HAIL_OF_ARROWS,
  ABILITY_JEBE_KHANS_SHOOTER,
  ABILITY_KALADIN_FIFTH,
  ABILITY_KALADIN_FIRST,
  ABILITY_KALADIN_FOURTH,
  ABILITY_KALADIN_SECOND,
  ABILITY_KALADIN_THIRD,
  ABILITY_LUCHE_BURNING_SUN,
  ABILITY_LUCHE_DIVINE_RAY,
  ABILITY_LUCHE_SHINE,
  ABILITY_LUCHE_SUN_GLORY,
  ABILITY_VLAD_POLKOVODETS,
} from "../../abilities";
import {
  HERO_DUOLINGO_ID,
  HERO_FEMTO_ID,
  HERO_FRISK_ID,
  HERO_GRIFFITH_ID,
  HERO_GUTS_ID,
  HERO_HASSAN_ID,
  HERO_JACK_RIPPER_ID,
  HERO_JEBE_ID,
  HERO_KALADIN_ID,
  HERO_LUCHE_ID,
} from "../../heroes";
import { buildBaseStats, getAttackRange, getMoveType, mapAbilityMetaList } from "../helpers";
import type { HeroMeta } from "../types";

export const HERO_REGISTRY_PART_2: HeroMeta[] = [
  {
    id: HERO_DUOLINGO_ID,
    name: "Duolingo",
    mainClass: "trickster",
    baseStats: buildBaseStats("trickster", HERO_DUOLINGO_ID),
    abilities: mapAbilityMetaList([
      ABILITY_DUOLINGO_BERSERKER,
      ABILITY_DUOLINGO_PUSH_NOTIFICATION,
      ABILITY_DUOLINGO_SKIP_CLASSES,
      ABILITY_DUOLINGO_STRICK,
    ]),
  },
  {
    id: HERO_FRISK_ID,
    name: "Frisk",
    mainClass: "assassin",
    baseStats: buildBaseStats("assassin", HERO_FRISK_ID),
    abilities: mapAbilityMetaList([
      ABILITY_FRISK_GENOCIDE,
      ABILITY_FRISK_ONE_PATH,
      ABILITY_FRISK_PACIFISM,
      ABILITY_FRISK_CLEAN_SOUL,
    ]),
  },
  {
    id: HERO_GRIFFITH_ID,
    name: "Griffith",
    mainClass: "knight",
    baseStats: buildBaseStats("knight", HERO_GRIFFITH_ID),
    abilities: mapAbilityMetaList([
      ABILITY_GRIFFITH_WRETCHED_MAN,
      ABILITY_VLAD_POLKOVODETS,
      ABILITY_GRIFFITH_FEMTO_REBIRTH,
    ]),
  },
  {
    id: HERO_FEMTO_ID,
    name: "Femto",
    mainClass: "knight",
    baseStats: {
      hp: getUnitDefinition("berserker").maxHp + 5,
      damage: getUnitDefinition("berserker").baseAttack,
      moveType: getMoveType("knight"),
      attackRange: getAttackRange("spearman"),
    },
    abilities: mapAbilityMetaList([
      ABILITY_FEMTO_GOD_HP,
      ABILITY_FEMTO_MULTI_BERSERK_SPEAR,
      ABILITY_FEMTO_DIVINE_MOVE,
      ABILITY_BERSERK_AUTO_DEFENSE,
    ]),
  },
  {
    id: HERO_GUTS_ID,
    name: "Guts",
    mainClass: "berserker",
    baseStats: buildBaseStats("berserker", HERO_GUTS_ID),
    abilities: mapAbilityMetaList([
      ABILITY_GUTS_ARBALET,
      ABILITY_GUTS_CANNON,
      ABILITY_GUTS_BERSERK_MODE,
    ]),
  },
  {
    id: HERO_JACK_RIPPER_ID,
    name: "Jack the Ripper",
    mainClass: "assassin",
    baseStats: buildBaseStats("assassin", HERO_JACK_RIPPER_ID),
    abilities: mapAbilityMetaList([
      ABILITY_JACK_RIPPER_DISMEMBERMENT,
      ABILITY_JACK_RIPPER_LEGEND_KILLER,
      ABILITY_JACK_RIPPER_SNARES,
      ABILITY_JACK_RIPPER_SURGERY,
    ]),
  },
  {
    id: HERO_JEBE_ID,
    name: "Jebe",
    mainClass: "archer",
    baseStats: buildBaseStats("archer", HERO_JEBE_ID),
    abilities: mapAbilityMetaList([
      ABILITY_JEBE_DURABLE,
      ABILITY_JEBE_KHANS_SHOOTER,
      ABILITY_JEBE_HAIL_OF_ARROWS,
      ABILITY_GENGHIS_KHAN_LEGEND_OF_THE_STEPPES,
      ABILITY_VLAD_POLKOVODETS,
    ]),
  },
  {
    id: HERO_HASSAN_ID,
    name: "Hassan-i Sabbah",
    mainClass: "assassin",
    baseStats: buildBaseStats("assassin", HERO_HASSAN_ID),
    abilities: mapAbilityMetaList([
      ABILITY_HASSAN_ONE_WITH_SAND,
      ABILITY_HASSAN_TRUE_ENEMY,
      ABILITY_HASSAN_ASSASIN_ORDER,
      ABILITY_VLAD_POLKOVODETS,
    ]),
  },
  {
    id: HERO_KALADIN_ID,
    name: "Kaladin Stormblessed",
    mainClass: "spearman",
    baseStats: buildBaseStats("spearman", HERO_KALADIN_ID),
    abilities: mapAbilityMetaList([
      ABILITY_KALADIN_FIRST,
      ABILITY_KALADIN_SECOND,
      ABILITY_KALADIN_THIRD,
      ABILITY_KALADIN_FOURTH,
      ABILITY_KALADIN_FIFTH,
    ]),
  },
  {
    id: HERO_LUCHE_ID,
    name: "Luche",
    mainClass: "spearman",
    baseStats: buildBaseStats("spearman", HERO_LUCHE_ID),
    abilities: mapAbilityMetaList([
      ABILITY_LUCHE_SHINE,
      ABILITY_LUCHE_BURNING_SUN,
      ABILITY_LUCHE_DIVINE_RAY,
      ABILITY_LUCHE_SUN_GLORY,
    ]),
  },
];
