import {
  ABILITY_ARTEMIDA_ACCURATE_ARROW,
  ABILITY_ARTEMIDA_MOONLIGHT_SHINE,
  ABILITY_ARTEMIDA_NATURE_MOVEMENT,
  ABILITY_ARTEMIDA_SILVER_CRESCENT,
  ABILITY_ASGORE_FIREBALL,
  ABILITY_ASGORE_FIRE_PARADE,
  ABILITY_ASGORE_SOUL_PARADE,
  ABILITY_CHIKATILO_ASSASSIN_MARK,
  ABILITY_CHIKATILO_DECOY,
  ABILITY_CHIKATILO_FALSE_TRAIL,
  ABILITY_CHIKATILO_TOUGH,
  ABILITY_DON_KIHOTE_MADNESS,
  ABILITY_DON_KIHOTE_SORROWFUL_COUNTENANCE,
  ABILITY_DON_KIHOTE_WINDMILLS,
  ABILITY_EL_SID_COMPEADOR_DEMON_DUELIST,
  ABILITY_EL_SID_COMPEADOR_KOLADA,
  ABILITY_EL_SID_COMPEADOR_TISONA,
  ABILITY_GENGHIS_KHAN_KHANS_DECREE,
  ABILITY_GENGHIS_KHAN_LEGEND_OF_THE_STEPPES,
  ABILITY_GENGHIS_KHAN_MONGOL_CHARGE,
  ABILITY_GROZNY_INVADE_TIME,
  ABILITY_GROZNY_TYRANT,
  ABILITY_KAISER_BUNKER,
  ABILITY_KAISER_CARPET_STRIKE,
  ABILITY_KAISER_DORA,
  ABILITY_KAISER_ENGINEERING_MIRACLE,
  ABILITY_LECHY_CONFUSE_TERRAIN,
  ABILITY_LECHY_GIANT,
  ABILITY_LECHY_GUIDE_TRAVELER,
  ABILITY_LECHY_NATURAL_STEALTH,
  ABILITY_LECHY_STORM,
  ABILITY_VLAD_FOREST,
  ABILITY_VLAD_INTIMIDATE,
  ABILITY_VLAD_POLKOVODETS,
  ABILITY_VLAD_STAKES,
} from "../../abilities";
import {
  HERO_ARTEMIDA_ID,
  HERO_ASGORE_ID,
  HERO_CHIKATILO_ID,
  HERO_DON_KIHOTE_ID,
  HERO_EL_CID_COMPEADOR_ID,
  HERO_GENGHIS_KHAN_ID,
  HERO_GRAND_KAISER_ID,
  HERO_GROZNY_ID,
  HERO_LECHY_ID,
  HERO_VLAD_TEPES_ID,
} from "../../heroes";
import { buildBaseStats, mapAbilityMetaList } from "../helpers";
import type { HeroMeta } from "../types";

export const HERO_REGISTRY_PART_1: HeroMeta[] = [
  {
    id: HERO_GRAND_KAISER_ID,
    name: "Grand Kaiser",
    mainClass: "archer",
    baseStats: buildBaseStats("archer", HERO_GRAND_KAISER_ID),
    abilities: mapAbilityMetaList([
      ABILITY_KAISER_BUNKER,
      ABILITY_KAISER_DORA,
      ABILITY_KAISER_CARPET_STRIKE,
      ABILITY_KAISER_ENGINEERING_MIRACLE,
    ]),
  },
  {
    id: HERO_GENGHIS_KHAN_ID,
    name: "Genghis Khan",
    mainClass: "rider",
    baseStats: buildBaseStats("rider", HERO_GENGHIS_KHAN_ID),
    abilities: mapAbilityMetaList([
      ABILITY_GENGHIS_KHAN_KHANS_DECREE,
      ABILITY_GENGHIS_KHAN_MONGOL_CHARGE,
      ABILITY_VLAD_POLKOVODETS,
      ABILITY_GENGHIS_KHAN_LEGEND_OF_THE_STEPPES,
    ]),
  },
  {
    id: HERO_CHIKATILO_ID,
    name: "Andrei Chikatilo",
    mainClass: "assassin",
    baseStats: buildBaseStats("assassin", HERO_CHIKATILO_ID),
    abilities: mapAbilityMetaList([
      ABILITY_CHIKATILO_TOUGH,
      ABILITY_CHIKATILO_FALSE_TRAIL,
      ABILITY_CHIKATILO_ASSASSIN_MARK,
      ABILITY_CHIKATILO_DECOY,
    ]),
  },
  {
    id: HERO_GROZNY_ID,
    name: "Ivan Grozny",
    mainClass: "berserker",
    baseStats: buildBaseStats("berserker", HERO_GROZNY_ID),
    abilities: mapAbilityMetaList([
      ABILITY_GROZNY_INVADE_TIME,
      ABILITY_VLAD_POLKOVODETS,
      ABILITY_GROZNY_TYRANT,
    ]),
  },
  {
    id: HERO_EL_CID_COMPEADOR_ID,
    name: "El Cid Compeador",
    mainClass: "knight",
    baseStats: buildBaseStats("knight", HERO_EL_CID_COMPEADOR_ID),
    abilities: mapAbilityMetaList([
      ABILITY_EL_SID_COMPEADOR_TISONA,
      ABILITY_VLAD_POLKOVODETS,
      ABILITY_EL_SID_COMPEADOR_KOLADA,
      ABILITY_EL_SID_COMPEADOR_DEMON_DUELIST,
    ]),
  },
  {
    id: HERO_LECHY_ID,
    name: "Lechy",
    mainClass: "trickster",
    baseStats: buildBaseStats("trickster", HERO_LECHY_ID),
    abilities: mapAbilityMetaList([
      ABILITY_LECHY_GIANT,
      ABILITY_LECHY_NATURAL_STEALTH,
      ABILITY_LECHY_GUIDE_TRAVELER,
      ABILITY_LECHY_CONFUSE_TERRAIN,
      ABILITY_LECHY_STORM,
    ]),
  },
  {
    id: HERO_VLAD_TEPES_ID,
    name: "Vlad III Tepes",
    mainClass: "spearman",
    baseStats: buildBaseStats("spearman", HERO_VLAD_TEPES_ID),
    abilities: mapAbilityMetaList([
      ABILITY_VLAD_POLKOVODETS,
      ABILITY_VLAD_INTIMIDATE,
      ABILITY_VLAD_STAKES,
      ABILITY_VLAD_FOREST,
    ]),
  },
  {
    id: HERO_ARTEMIDA_ID,
    name: "Artemida",
    mainClass: "archer",
    baseStats: buildBaseStats("archer", HERO_ARTEMIDA_ID),
    abilities: mapAbilityMetaList([
      ABILITY_ARTEMIDA_ACCURATE_ARROW,
      ABILITY_ARTEMIDA_MOONLIGHT_SHINE,
      ABILITY_ARTEMIDA_SILVER_CRESCENT,
      ABILITY_ARTEMIDA_NATURE_MOVEMENT,
    ]),
  },
  {
    id: HERO_ASGORE_ID,
    name: "Asgore Dreemurr",
    mainClass: "knight",
    baseStats: buildBaseStats("knight", HERO_ASGORE_ID),
    abilities: mapAbilityMetaList([
      ABILITY_ASGORE_FIREBALL,
      ABILITY_ASGORE_FIRE_PARADE,
      ABILITY_ASGORE_SOUL_PARADE,
    ]),
  },
  {
    id: HERO_DON_KIHOTE_ID,
    name: "Don Kihote",
    mainClass: "rider",
    baseStats: buildBaseStats("rider", HERO_DON_KIHOTE_ID),
    abilities: mapAbilityMetaList([
      ABILITY_DON_KIHOTE_SORROWFUL_COUNTENANCE,
      ABILITY_DON_KIHOTE_WINDMILLS,
      ABILITY_DON_KIHOTE_MADNESS,
      ABILITY_VLAD_POLKOVODETS,
    ]),
  },
];
