import type { AbilitySpec } from "../types";
import * as ids from "../constants";

export const ABILITY_SPECS_PART_4: Record<string, AbilitySpec> = {
  [ids.ABILITY_METTATON_POPPINS]: {
    id: ids.ABILITY_METTATON_POPPINS,
    displayName: "Mettaton Poppins",
    kind: "active",
    description:
      "Spend 3 Rating. Choose a 3x3 center on your attack line and attack all units in that area.",
    actionCost: {
      consumes: { action: true },
    },
  },
  [ids.ABILITY_METTATON_WORK_ON_CAMERA]: {
    id: ids.ABILITY_METTATON_WORK_ON_CAMERA,
    displayName: "Work on Camera",
    kind: "passive",
    description: "Cannot enter stealth. Gains Rider movement pattern.",
  },
  [ids.ABILITY_METTATON_EX]: {
    id: ids.ABILITY_METTATON_EX,
    displayName: "Mettaton EX",
    kind: "impulse",
    description:
      "At the start of Mettaton's turn, unlock Stage Phenomenon and Laser when Rating is at least 5. Rating is not spent.",
  },
  [ids.ABILITY_METTATON_STAGE_PHENOMENON]: {
    id: ids.ABILITY_METTATON_STAGE_PHENOMENON,
    displayName: "Stage Phenomenon",
    kind: "passive",
    description: "After EX: each attack action grants +1 Rating.",
  },
  [ids.ABILITY_METTATON_LASER]: {
    id: ids.ABILITY_METTATON_LASER,
    displayName: "Laser",
    kind: "active",
    description:
      "After EX, spend 3 Rating. Choose an attack line and attack all units on it.",
    actionCost: {
      consumes: { action: true },
    },
  },
  [ids.ABILITY_METTATON_NEO]: {
    id: ids.ABILITY_METTATON_NEO,
    displayName: "Mettaton NEO",
    kind: "impulse",
    description:
      "At the start of Mettaton's turn, unlock Rider Feature, Berserker Multiclass, and Grace when Rating is at least 10. Rating is not spent.",
  },
  [ids.ABILITY_METTATON_RIDER_FEATURE]: {
    id: ids.ABILITY_METTATON_RIDER_FEATURE,
    displayName: "Rider Feature",
    kind: "passive",
    description: "After NEO: path attacks trigger while moving in Rider mode.",
  },
  [ids.ABILITY_METTATON_BERSERKER_MULTICLASS]: {
    id: ids.ABILITY_METTATON_BERSERKER_MULTICLASS,
    displayName: "Berserker Multiclass",
    kind: "passive",
    description: "After NEO: gain Berserker feature bundle.",
  },
  [ids.ABILITY_METTATON_GRACE]: {
    id: ids.ABILITY_METTATON_GRACE,
    displayName: "Grace",
    kind: "passive",
    description: "After NEO: each defense roll attempt grants +1 Rating.",
  },
  [ids.ABILITY_METTATON_FINAL_CHORD]: {
    id: ids.ABILITY_METTATON_FINAL_CHORD,
    displayName: "Final Chord",
    kind: "phantasm",
    description:
      "Spend 12 Rating. Attack all enemies on all available attack lines for 3 damage on hit.",
    actionCost: {
      consumes: { action: true },
    },
  },
  [ids.ABILITY_RIVER_PERSON_BOAT]: {
    id: ids.ABILITY_RIVER_PERSON_BOAT,
    displayName: "Boat",
    kind: "active",
    description:
      "Spend one movement action to move River Person, optionally carrying one adjacent ally and dropping that ally adjacent to the final cell.",
  },
  [ids.ABILITY_RIVER_PERSON_BOATMAN]: {
    id: ids.ABILITY_RIVER_PERSON_BOATMAN,
    displayName: "Boatman",
    kind: "active",
    description:
      "Spend action to gain one additional movement action this turn.",
    actionCost: {
      consumes: { action: true },
    },
  },
  [ids.ABILITY_RIVER_PERSON_GUIDE_OF_SOULS]: {
    id: ids.ABILITY_RIVER_PERSON_GUIDE_OF_SOULS,
    displayName: "Guide of Souls",
    kind: "passive",
    description:
      "Immune to arena storm effects and storm attack restrictions.",
  },
  [ids.ABILITY_RIVER_PERSON_TRA_LA_LA]: {
    id: ids.ABILITY_RIVER_PERSON_TRA_LA_LA,
    displayName: "Tra-la-la",
    kind: "phantasm",
    description:
      "At full 4 charges: choose adjacent enemy, move in a straight line, touched allies that can legally attack strike that enemy once, then drop the enemy adjacent.",
    maxCharges: 4,
    chargesPerUse: 4,
    actionCost: {
      consumes: { action: true },
    },
  },
  [ids.ABILITY_TRICKSTER_AOE]: {
    id: ids.ABILITY_TRICKSTER_AOE,
    displayName: "Trickster AoE",
    kind: "active",
    description: "5x5 AoE (radius 2). Hits allies (not self).",
    actionCost: {
      consumes: { attack: true, action: true },
    },
  },
  [ids.ABILITY_TEST_MULTI_SLOT]: {
    id: ids.ABILITY_TEST_MULTI_SLOT,
    displayName: "Test Multi Slot",
    kind: "active",
    description: "Consumes move and attack slots.",
    actionCost: {
      consumes: { move: true, attack: true },
    },
  },
  [ids.ABILITY_KAISER_BUNKER]: {
    id: ids.ABILITY_KAISER_BUNKER,
    displayName: "Bunker",
    kind: "passive",
    description: "Instead of stealth, you have the ability to enter a bunker (4-6), your location is visible, but any hit on you will only deal 1 damage.",
  },
  [ids.ABILITY_KAISER_DORA]: {
    id: ids.ABILITY_KAISER_DORA,
    displayName: "Dora",
    kind: "active",
    description: "Without leaving the bunker, you can attack, select a 3x3 area, the center of this area should be on the line of your possible attack, attack everyone in this area.",
    maxCharges: 2,
    chargesPerUse: 2,
    actionCost: {
      consumes: { action: true },
    },
  },
  [ids.ABILITY_KAISER_CARPET_STRIKE]: {
    id: ids.ABILITY_KAISER_CARPET_STRIKE,
    displayName: "Carpet Strike",
    kind: "impulse",
    description: "It's time to kill all enemies of the Reich. Roll 2d9 - the result is the center of a 5x5 area. Attack everyone in that area. Carpet Bombing doesn't hit Kaiser if he's in the Bunker. The ability always deals 1 damage.",
    maxCharges: 3,
    chargesPerUse: 3,
  },
  [ids.ABILITY_KAISER_ENGINEERING_MIRACLE]: {
    id: ids.ABILITY_KAISER_ENGINEERING_MIRACLE,
    displayName: "Engineering Miracle",
    kind: "impulse",
    description: "You're showing by example what Nazi cyborgs are like. You gain the multi-class of rider and berserker, and the Dora bitch doesn't require more charges. However, you lose the ability to enter stealth and bunkers, and carpet bombings won't affect you in this state.",
    chargeUnlimited: true,
    triggerCharges: 4,
  },
  [ids.ABILITY_VLAD_POLKOVODETS]: {
    id: ids.ABILITY_VLAD_POLKOVODETS,
    displayName: "Commander",
    kind: "passive",
    description: "Allies within one cell of this figure receive +1 damage (does not work on the figure itself, does not stack, for riders, to receive the damage buff you must either start moving or end in the commander's aura).",
  },
  [ids.ABILITY_VLAD_INTIMIDATE]: {
    id: ids.ABILITY_VLAD_INTIMIDATE,
    displayName: "Intimidating Stare",
    kind: "passive",
    description: "If you defend successfully, you can force the attacker to move one unoccupied square.",
  },
  [ids.ABILITY_VLAD_STAKES]: {
    id: ids.ABILITY_VLAD_STAKES,
    displayName: "Field of Stakes",
    kind: "impulse",
    description: "Place 3 hidden stakes at battle start and from 2nd turn.",
  },
  [ids.ABILITY_VLAD_FOREST]: {
    id: ids.ABILITY_VLAD_FOREST,
    displayName: "Forest of the Dead",
    kind: "impulse",
    description: "Automatic phantasm: at the start of Vlad's turn, when he owns 9 stakes, consume the 9 oldest stakes and choose a 3x3 area (2 damage and root).",
  },
  [ids.ABILITY_DUOLINGO_LONG_LIVED]: {
    id: ids.ABILITY_DUOLINGO_LONG_LIVED,
    displayName: "Long-lived",
    kind: "passive",
    description: "Duolingo gains +2 max HP.",
  },
  [ids.ABILITY_DUOLINGO_STRICK]: {
    id: ids.ABILITY_DUOLINGO_STRICK,
    displayName: "Daily Streak",
    kind: "passive",
    description: "Deal +1 damage to creatures Duolingo successfully hit on his previous turn.",
  },
  [ids.ABILITY_DUOLINGO_SKIP_CLASSES]: {
    id: ids.ABILITY_DUOLINGO_SKIP_CLASSES,
    displayName: "Missed Lessons",
    kind: "passive",
    description: "Gain 1 Missed Lesson whenever an attack misses. This counter is unbounded.",
    chargeUnlimited: true,
    isSpecialCounter: true,
  },
  [ids.ABILITY_DUOLINGO_PUSH_NOTIFICATION]: {
    id: ids.ABILITY_DUOLINGO_PUSH_NOTIFICATION,
    displayName: "Push Notification",
    kind: "active",
    description: "Its own counter gains +1 at the start of Duolingo's turn. Spend either 3 of that counter or 3 Missed Lessons; both paths consume Movement. Choose a living creature, then teleport to a legal empty cell within 2 cells of it. Exit stealth.",
    maxCharges: 3,
    chargesPerUse: 3,
    actionCost: { consumes: { move: true } },
  },
  [ids.ABILITY_DUOLINGO_BERSERKER]: {
    id: ids.ABILITY_DUOLINGO_BERSERKER,
    displayName: "I Reminded You!!!",
    kind: "impulse",
    description: "At 12 or more Missed Lessons, permanently gain Berserker multiclass. The counter is not spent.",
    triggerCharges: 12,
  },
  [ids.ABILITY_LUCHE_LONG_LIVED]: {
    id: ids.ABILITY_LUCHE_LONG_LIVED,
    displayName: "Long-lived",
    kind: "passive",
    description: "Luche gains +2 max HP.",
  },
  [ids.ABILITY_LUCHE_SUN_GLORY]: {
    id: ids.ABILITY_LUCHE_SUN_GLORY,
    displayName: "Glory of the Sun",
    kind: "passive",
    description: "Gain 1 Sun whenever Luche successfully dodges an enemy attack. Sun is unbounded.",
    chargeUnlimited: true,
    isSpecialCounter: true,
  },
  [ids.ABILITY_LUCHE_SHINE]: {
    id: ids.ABILITY_LUCHE_SHINE,
    displayName: "Radiance",
    kind: "passive",
    description: "Radiance — Passive. When a figure successfully hits Luche, that figure becomes Blinded until the end of its next turn.",
  },
  [ids.ABILITY_LUCHE_DIVINE_RAY]: {
    id: ids.ABILITY_LUCHE_DIVINE_RAY,
    displayName: "Light Ray",
    kind: "impulse",
    description: "Its own counter gains +1 at the start of Luche's turn. At 2, it activates as a start-turn impulse without spending Sun or Action. During Luche's turn it may instead spend 2 Sun and Action. Choose a straight line or the area around Luche; failed defenses apply Blind until the end of that enemy's next turn.",
    maxCharges: 2,
    chargesPerUse: 2,
    actionCost: { consumes: { action: true } },
  },
  [ids.ABILITY_LUCHE_BURNING_SUN]: {
    id: ids.ABILITY_LUCHE_BURNING_SUN,
    displayName: "Falling Sun",
    kind: "phantasm",
    description: "Spend 5 Sun and Action. Attack every enemy in Luche's attack area for 2 damage on failed defense and apply Blind.",
    actionCost: { consumes: { action: true } },
  },
  [ids.ABILITY_KANEKI_GHOUL]: {
    id: ids.ABILITY_KANEKI_GHOUL,
    displayName: "Ghoul",
    kind: "passive",
    description: "Kaneki gains +2 max HP.",
  },
  [ids.ABILITY_KANEKI_RC_CELLS]: {
    id: ids.ABILITY_KANEKI_RC_CELLS,
    displayName: "RC Cells",
    kind: "passive",
    description: "Gain 1 RC Cell on a hit and an additional 3 RC Cells on a kill. RC Cells are unbounded.",
    chargeUnlimited: true,
    isSpecialCounter: true,
  },
  [ids.ABILITY_KANEKI_RINKAKU_KAGUNE]: {
    id: ids.ABILITY_KANEKI_RINKAKU_KAGUNE,
    displayName: "Rinkaku Kagune",
    kind: "passive",
    description: "Kaneki also has Assassin movement.",
  },
  [ids.ABILITY_KANEKI_REGENERATION]: {
    id: ids.ABILITY_KANEKI_REGENERATION,
    displayName: "Regeneration",
    kind: "active",
    description: "Spend a chosen number of RC Cells to heal the same amount, up to max HP. Uses Action.",
    actionCost: { consumes: { action: true } },
  },
  [ids.ABILITY_KANEKI_SCOLOPENDRA]: {
    id: ids.ABILITY_KANEKI_SCOLOPENDRA,
    displayName: "Centipede",
    kind: "phantasm",
    description: "While RC Cells are greater than 5, permanently gain Rider movement and path features and may spend Action for an extra movement.",
    triggerCharges: 6,
  },
  [ids.ABILITY_ZORO_CHEATED_DEATH]: {
    id: ids.ABILITY_ZORO_CHEATED_DEATH,
    displayName: "Cheated Death",
    kind: "passive",
    description: "Zoro gains +2 max HP.",
  },
  [ids.ABILITY_ZORO_DETERMINATION]: {
    id: ids.ABILITY_ZORO_DETERMINATION,
    displayName: "Determination",
    kind: "passive",
    description: "Gain 1 Determination after every successful attack. Determination is unbounded.",
    chargeUnlimited: true,
    isSpecialCounter: true,
  },
  [ids.ABILITY_ZORO_ONI_GIRI]: {
    id: ids.ABILITY_ZORO_ONI_GIRI,
    displayName: "Oni Giri",
    kind: "active",
    description: "Its own counter gains +1 at the start of Zoro's turn. Spend either 2 of that counter or 2 Determination; both paths consume Action and Movement. Choose an enemy on a straight line, move directly before or behind it, then attack it.",
    maxCharges: 2,
    chargesPerUse: 2,
    actionCost: { consumes: { action: true, move: true } },
  },
  [ids.ABILITY_ZORO_3_SWORD_STYLE]: {
    id: ids.ABILITY_ZORO_3_SWORD_STYLE,
    displayName: "Santoryu",
    kind: "passive",
    description: "A basic attack may target one or two different legal creatures and consumes Action once.",
  },
  [ids.ABILITY_ZORO_ASURA]: {
    id: ids.ABILITY_ZORO_ASURA,
    displayName: "Asura: Nine-Sword Style",
    kind: "phantasm",
    description: "Spend 6 Determination and Action. Attack all enemies in Trickster area with +1 damage.",
    actionCost: { consumes: { action: true } },
  },
  [ids.ABILITY_DON_KIHOTE_HARDY]: {
    id: ids.ABILITY_DON_KIHOTE_HARDY,
    displayName: "Hardy",
    kind: "passive",
    description: "Don Quixote gains +1 max HP.",
  },
  [ids.ABILITY_DON_KIHOTE_SORROWFUL_COUNTENANCE]: {
    id: ids.ABILITY_DON_KIHOTE_SORROWFUL_COUNTENANCE,
    displayName: "Knight of the Sorrowful Image",
    kind: "passive",
    description: "After an enemy attack damages Don Quixote, optionally make a free legal 1-cell reaction move without spending Movement.",
  },
  [ids.ABILITY_DON_KIHOTE_WINDMILLS]: {
    id: ids.ABILITY_DON_KIHOTE_WINDMILLS,
    displayName: "Attack on Windmills",
    kind: "active",
    description: "Spend 3 charges and Movement. Declare one enemy hero the Giant and dash toward it on a straight line. One crossed enemy takes 1 damage and is repositioned by its owner; only the Giant is attacked.",
    maxCharges: 3,
    chargesPerUse: 3,
    actionCost: { consumes: { move: true } },
  },
  [ids.ABILITY_DON_KIHOTE_MADNESS]: {
    id: ids.ABILITY_DON_KIHOTE_MADNESS,
    displayName: "Madness of the Knight",
    kind: "phantasm",
    description: "On death, choose a straight direction and make a final +1 damage attack against every enemy on that line.",
  },
  [ids.ABILITY_JACK_RIPPER_RESILIENT]: {
    id: ids.ABILITY_JACK_RIPPER_RESILIENT,
    displayName: "Resilient",
    kind: "passive",
    description: "Jack gains +1 max HP.",
  },
  [ids.ABILITY_JACK_RIPPER_COVERING_TRACKS]: {
    id: ids.ABILITY_JACK_RIPPER_COVERING_TRACKS,
    displayName: "Covering Tracks",
    kind: "passive",
    description: "If Jack would place a 6th snare while 5 snares are already on the board, choose one existing snare to explode. Creatures within radius 1 roll 1d6; on 1-4 they take 1 damage, on 5-6 they avoid it.",
  },
  [ids.ABILITY_JACK_RIPPER_SURGERY]: {
    id: ids.ABILITY_JACK_RIPPER_SURGERY,
    displayName: "Surgeon",
    kind: "passive",
    description: "After Jack deals damage, his owner privately knows the target's remaining HP.",
  },
  [ids.ABILITY_JACK_RIPPER_SNARES]: {
    id: ids.ABILITY_JACK_RIPPER_SNARES,
    displayName: "Maniac Traps",
    kind: "impulse",
    description: "At the start of Jack's turn, place a hidden trap on any cell. Its owner can see it. A creature entering it stops and cannot move until its next turn starts; then the trap disappears.",
  },
  [ids.ABILITY_JACK_RIPPER_DISMEMBERMENT]: {
    id: ids.ABILITY_JACK_RIPPER_DISMEMBERMENT,
    displayName: "Holy Mother of Slaughter",
    kind: "phantasm",
    description: "Once per game, spend Action to attack a target standing on Jack's trap four times; each failed defense deals 3 damage.",
    actionCost: { consumes: { action: true } },
  },
  [ids.ABILITY_ARTEMIDA_GOD]: {
    id: ids.ABILITY_ARTEMIDA_GOD,
    displayName: "God",
    kind: "passive",
    description: "Artemis gains +5 max HP and starts at her full modified HP.",
  },
  [ids.ABILITY_ARTEMIDA_ACCURATE_ARROW]: {
    id: ids.ABILITY_ARTEMIDA_ACCURATE_ARROW,
    displayName: "Precise Arrow",
    kind: "passive",
    description: "Attack doubles automatically hit.",
  },
  [ids.ABILITY_ARTEMIDA_NATURE_MOVEMENT]: {
    id: ids.ABILITY_ARTEMIDA_NATURE_MOVEMENT,
    displayName: "Natural Movement",
    kind: "passive",
    description: "Artemis also has Trickster movement.",
  },
  [ids.ABILITY_ARTEMIDA_MOONLIGHT_SHINE]: {
    id: ids.ABILITY_ARTEMIDA_MOONLIGHT_SHINE,
    displayName: "Moon Insight",
    kind: "impulse",
    description: "At the start of Artemis's turn, spend 3 charges as an impulse. Choose a 3x3 area centered on her legal Archer attack line; enemies there exit stealth.",
    maxCharges: 3,
    chargesPerUse: 3,
  },
  [ids.ABILITY_ARTEMIDA_SILVER_CRESCENT]: {
    id: ids.ABILITY_ARTEMIDA_SILVER_CRESCENT,
    displayName: "Silver Moon Sickle",
    kind: "phantasm",
    description: "Spend 5 charges and Action. Choose an endpoint on a legal attack line and attack every unit on the line up to that endpoint and adjacent cells for 2 damage on failed defense.",
    maxCharges: 5,
    chargesPerUse: 5,
    actionCost: { consumes: { action: true } },
  },
  [ids.ABILITY_ARTEMIDA_STEALTH]: {
    id: ids.ABILITY_ARTEMIDA_STEALTH,
    displayName: "Stealth",
    kind: "passive",
    description: "Artemis can enter stealth on a roll of 6.",
  },
};
