/** Type-only links to the public DTO producers. Never describe database models here. */
import type { toAuthUserDto } from "../auth/userDto";
import type { toAccessCredentialsDto, toSessionCredentialsDto } from "../routes/authRoutes";
import type { RankTier } from "../rating/rankTiers";
import type { toOwnProfileDto, toPublicProfileDto } from "../profile/dto";
import type { MatchService } from "../services/matchService";
import type { MatchHistoryService } from "../services/matchHistoryService";
import type { MatchActionService } from "../services/matchActionService";
import type { PlayerStatisticsService } from "../services/playerStatisticsService";
import type { RatingService } from "../services/ratingService";
import type { LeaderboardService } from "../services/leaderboardService";
import type { ReplayQueryService } from "../services/replayQueryService";
import type { AdminService } from "../services/adminService";
import type { AuditLogReader } from "../services/auditLogService";
import type { MatchmakingService } from "../services/matchmakingService";
import type { listRoomSummaries } from "../store";
import type { readLeaderboardConfig } from "../leaderboard/config";
import type { getTestRoomCapabilities } from "../testRoom/access";
import type { HeroMeta } from "rules";
import type { toCreatedRoomDto, toCreatedGameDto, serverInfo } from "../routes";
import type { healthStatus } from "../routes/healthRoutes";

export type CurrentUser = { user: ReturnType<typeof toAuthUserDto> };
export type AuthCredentials = ReturnType<typeof toAccessCredentialsDto>;
export type AuthSessionCredentials = ReturnType<typeof toSessionCredentialsDto>;
export type RatingRankTier = RankTier;
export type OwnProfile = { profile: ReturnType<typeof toOwnProfileDto> };
export type PublicProfile = { profile: ReturnType<typeof toPublicProfileDto> };
export type MatchDetails = Awaited<ReturnType<MatchService["getFinishedMatchDetails"]>>;
export type MatchHistory = Awaited<ReturnType<MatchHistoryService["getUserMatchHistory"]>>;
export type MatchActions = Awaited<
  ReturnType<MatchActionService["getCompletedMatchActionHistory"]>
>;
export type PlayerStatistics = Awaited<ReturnType<PlayerStatisticsService["getPlayerStatistics"]>>;
export type PlayerModeRating = Awaited<ReturnType<RatingService["getPlayerRating"]>>;
export type PlayerRatings = Awaited<ReturnType<RatingService["getAllPlayerRatings"]>>;
export type RatingHistory = Awaited<ReturnType<RatingService["getRatingHistory"]>>;
export type Leaderboard = Awaited<ReturnType<LeaderboardService["getLeaderboard"]>>;
export type ReplayMetadata = Awaited<ReturnType<ReplayQueryService["getMetadata"]>>;
export type ReplayState = Awaited<ReturnType<ReplayQueryService["getState"]>>;
export type AdminUsers = Awaited<ReturnType<AdminService["listUsers"]>>;
export type AdminUser = Awaited<ReturnType<AdminService["getUser"]>>;
export type AdminUserMutation = Awaited<ReturnType<AdminService["setBlocked"]>>;
export type AdminMatches = Awaited<ReturnType<AdminService["listMatches"]>>;
export type AdminMatch = Awaited<ReturnType<AdminService["getMatch"]>>;
export type AdminMatchActions = Awaited<ReturnType<AdminService["listActions"]>>;
export type AdminSummary = Awaited<ReturnType<AdminService["summary"]>>;
export type AuditEvents = Awaited<ReturnType<AuditLogReader["list"]>>;
export type MatchmakingStatus = ReturnType<MatchmakingService["getSnapshot"]>;
export type Rooms = ReturnType<typeof listRoomSummaries>;
export type Room = Rooms[number];
export type CreatedRoom = ReturnType<typeof toCreatedRoomDto>;
export type CreatedGame = ReturnType<typeof toCreatedGameDto>;
export type CompetitiveConfig = ReturnType<typeof readLeaderboardConfig>;
export type Capabilities = { testRooms: ReturnType<typeof getTestRoomCapabilities> };
export type Hero = HeroMeta;
export type Heroes = HeroMeta[];
export type ServerInfo = ReturnType<typeof serverInfo>;
export type Health = ReturnType<typeof healthStatus>;

export interface ApiResponses {
  CurrentUser: CurrentUser;
  AuthCredentials: AuthCredentials;
  AuthSessionCredentials: AuthSessionCredentials;
  RankTier: RatingRankTier;
  OwnProfile: OwnProfile;
  PublicProfile: PublicProfile;
  MatchDetails: MatchDetails;
  MatchHistory: MatchHistory;
  MatchActions: MatchActions;
  PlayerStatistics: PlayerStatistics;
  PlayerModeRating: PlayerModeRating;
  PlayerRatings: PlayerRatings;
  RatingHistory: RatingHistory;
  Leaderboard: Leaderboard;
  ReplayMetadata: ReplayMetadata;
  ReplayState: ReplayState;
  AdminUsers: AdminUsers;
  AdminUser: AdminUser;
  AdminUserMutation: AdminUserMutation;
  AdminMatches: AdminMatches;
  AdminMatch: AdminMatch;
  AdminMatchActions: AdminMatchActions;
  AdminSummary: AdminSummary;
  AuditEvents: AuditEvents;
  MatchmakingStatus: MatchmakingStatus;
  Rooms: Rooms;
  Room: Room;
  CreatedRoom: CreatedRoom;
  CreatedGame: CreatedGame;
  CompetitiveConfig: CompetitiveConfig;
  Capabilities: Capabilities;
  Hero: Hero;
  Heroes: Heroes;
  ServerInfo: ServerInfo;
  Health: Health;
}
