export const FRISK_PACIFISM_HUGS_COST = 3;
export const FRISK_PACIFISM_CHILDS_CRY_COST = 5;
export const FRISK_PACIFISM_WARM_WORDS_COST = 10;
export const FRISK_GENOCIDE_SUBSTITUTION_COST = 3;
export const FRISK_GENOCIDE_KEEN_EYE_COST = 5;
export const FRISK_GENOCIDE_PRECISION_STRIKE_COST = 10;
