import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { chromium } from "playwright-core";

// Local production-Board smoke harness; fixtures are generated by real rules.
// No database, account, gameplay RNG or production route is changed.
const webRoot = fileURLToPath(new URL("../", import.meta.url));
const root = path.resolve(webRoot, "../..");
const output = path.join(webRoot, "test-results/sans");
const url = "http://127.0.0.1:5188";
const executablePath = [
  process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,
  "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "/usr/bin/chromium",
].find((p) => p && existsSync(p));
assert(executablePath, "Local Chromium browser required");
await mkdir(output, { recursive: true });
const helpers = path
  .join(root, "packages/rules/src/tests/helpers/testUtils.ts")
  .replaceAll("\\", "/");
const rules = path.join(root, "packages/rules/src/index.ts").replaceAll("\\", "/");
await writeFile(
  path.join(output, "fixtures.ts"),
  `
import { writeFileSync } from "node:fs";
import { setupSansState, setUnit, toBattleState, initKnowledgeForOwners, makeRngSequence, makeAttackWinRng, resolvePendingRollOnce } from ${JSON.stringify(helpers)};
import { applyAction, makePlayerView, projectEventsForRecipient, ABILITY_SANS_GASTER_BLASTER } from ${JSON.stringify(rules)};
const f = setupSansState();
const targets = Object.values(f.state.units).filter(u => u.owner === "P2" && ["archer","knight","spearman"].includes(u.class)).slice(0,3);
const wrap = (result, revision) => Object.fromEntries(["P1","P2"].map(player => [player, {
  view: makePlayerView(result.state, player), batch: { streamId: "sans-smoke", revision,
  events: projectEventsForRecipient(result.state, result.events, player).map((e,i) => ({...e,eventId:"E"+revision+":"+i})) }
}]));
const baseline = state => wrap({state,events:[]},0);
let state = setUnit(f.state,f.sans.id,{position:{col:1,row:3},charges:{...f.sans.charges,[ABILITY_SANS_GASTER_BLASTER]:2}});
targets.forEach((u,i) => state=setUnit(state,u.id,{position:{col:2+i,row:4+i},hp:5}));
state=setUnit(state,f.ally.id,{position:{col:5,row:7},hp:5});
state=initKnowledgeForOwners(toBattleState(state,"P1",f.sans.id));
const gasterBefore=baseline(state);
let result=applyAction(state,{type:"useAbility",unitId:f.sans.id,abilityId:ABILITY_SANS_GASTER_BLASTER,payload:{target:{col:2,row:4}}},makeRngSequence([]));
const gaster=[wrap(result,1)];
while(result.state.pendingRoll){const p=result.state.pendingRoll;result=applyAction(result.state,{type:"resolvePendingRoll",player:p.player,pendingRollId:p.id},makeRngSequence(p.kind.endsWith("_attackerRoll")?[0.8,0.5]:[0.01,0.2]));gaster.push(wrap(result,gaster.length+1));}
state=setUnit(f.state,f.sans.id,{hp:1,position:{col:4,row:4},sansUnbelieverUnlocked:true});
state=setUnit(state,f.enemy.id,{hp:2,position:{col:4,row:5}});
state=initKnowledgeForOwners(toBattleState(state,"P2",f.enemy.id));
const lastBefore=baseline(state), rng=makeAttackWinRng(1);
result=applyAction(state,{type:"attack",attackerId:f.enemy.id,defenderId:f.sans.id},rng);
let lethal=[...result.events];
while(result.state.pendingRoll?.kind!=="selectLastAttackTarget"){result=resolvePendingRollOnce(result.state,rng);lethal.push(...result.events);}
const pending=wrap({...result,events:lethal},1);
const selected=applyAction(result.state,{type:"resolvePendingRoll",player:"P1",pendingRollId:result.state.pendingRoll.id,choice:{type:"sansLastAttackTarget",targetId:f.enemy.id}},makeRngSequence([]));
const cursed=setUnit(selected.state,f.enemy.id,{hp:2});
const activation={...cursed,currentPlayer:"P2",activeUnitId:null,turnNumber:cursed.turnNumber+1,turnQueue:[f.enemy.id],turnQueueIndex:0,turnOrder:[f.enemy.id],turnOrderIndex:0};
const tick=applyAction(activation,{type:"unitStartTurn",unitId:f.enemy.id},makeRngSequence([]));
writeFileSync(${JSON.stringify(path.join(output, "fixtures.json"))},JSON.stringify({sansId:f.sans.id,allyId:f.ally.id,targetId:f.enemy.id,gasterBefore,gaster,lastBefore,pending,selected:wrap(selected,2),tick:wrap(tick,3)}));
`,
);
const fixtureRun = spawnSync(
  process.execPath,
  [
    path.join(root, "node_modules/tsx/dist/cli.mjs"),
    "--tsconfig",
    path.join(root, "tsconfig.tests.json"),
    path.join(output, "fixtures.ts"),
  ],
  { cwd: root, windowsHide: true, encoding: "utf8" },
);
assert.equal(fixtureRun.status, 0, fixtureRun.stderr);
await writeFile(
  path.join(output, "index.html"),
  '<div id="root"></div><script type="module" src="./harness.tsx"></script>',
);
await writeFile(
  path.join(output, "harness.tsx"),
  `
import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {Board} from "/src/components/Board.tsx";
import {PendingBoardNotice} from "/src/game/gameshell-content/components/PendingBoardNotice.tsx";
import {OpponentDecisionStatus} from "/src/game/gameshell-content/components/OpponentDecisionStatus.tsx";
import {buildPendingPreview} from "/src/game/targeting/buildPendingPreview.ts";
import {sfxPlayer} from "/src/features/sfx/sfxPlayer.ts";
import {preloadSansSounds,preloadCoreSounds} from "/src/features/sfx/audioPreload.ts";
import data from "./fixtures.json";
import "/src/styles.css";
window.sansAudio=[];
const originalPlay=sfxPlayer.play.bind(sfxPlayer);
sfxPlayer.play=(cue)=>{const played=originalPlay(cue);window.sansAudio.push({key:cue.key,time:Date.now(),played});return played;};
function App(){
 const [scenario,setScenario]=useState("gaster"),[frame,setFrame]=useState(data.gasterBefore),[index,setIndex]=useState(-1),[session,setSession]=useState("initial");
 const reset=(kind)=>{setScenario(kind);setFrame(kind==="gaster"?data.gasterBefore:data.lastBefore);setIndex(-1);setSession("reset"+Date.now());window.sansAudio=[];};
 const next=()=>{const i=index+1;setIndex(i);setFrame(scenario==="gaster"?data.gaster[i]:data.pending);};
 const reconnect=()=>{setSession("reconnect"+Date.now());setFrame(old=>Object.fromEntries(Object.entries(old).map(([player,v])=>[player,{...v,batch:null}])));window.sansAudio=[];};
 const choose=(choice)=>{if(choice.targetId!==data.targetId)throw Error("unexpected target");setFrame(data.selected);};
 return <><div><button onClick={async()=>{await sfxPlayer.ensureAudioReady();await Promise.all([preloadSansSounds(),preloadCoreSounds("gameplay")]);document.body.dataset.audio="ready";}}>Enable audio</button>
 <button onClick={()=>reset("gaster")}>Gaster baseline</button><button onClick={()=>reset("last")}>Last Attack baseline</button>
 <button onClick={next}>Next manual decision</button><button onClick={reconnect}>Reconnect baseline</button><button onClick={()=>setFrame(data.tick)}>Start cursed own turn</button></div>
 <div style={{display:"flex"}}>{["P1","P2"].map(player=><section key={player} data-board={player} style={{width:540}}>
 <Board view={frame[player].view} playerId={player} selectedUnitId={null} highlightedCells={{}} boardPreview={buildPendingPreview(frame[player].view)}
 visualEffectsEnabled eventBatch={frame[player].batch} effectSessionKey={session} onSelectUnit={()=>{}} onCellClick={()=>{document.body.dataset.clicked="yes";}}/>
 {frame[player].view.pendingRoll?.kind==="selectLastAttackTarget"?<div data-pending-owner><PendingBoardNotice pendingRollKind="selectLastAttackTarget"
 pendingRollContext={frame[player].view.pendingRoll.context} units={frame[player].view.rosterUnits} pendingQueueCount={0} stakeSelections={[]} stakeLimit={0} hassanAssassinOrderSelections={[]}
 onResolveChoice={choose}/></div>:null}
 {frame[player].view.pendingDecision?.viewerCanRespond===false&&scenario==="last"?<OpponentDecisionStatus presentation={frame[player].view.pendingDecision.opponentStatus}/>:null}
 </section>)}</div></>;
}
createRoot(document.getElementById("root")).render(<App/>);
`,
);
const server = spawn(
  process.execPath,
  [
    path.join(root, "node_modules/vite/bin/vite.js"),
    "--host",
    "127.0.0.1",
    "--port",
    "5188",
    "--strictPort",
  ],
  { cwd: webRoot, windowsHide: true, stdio: "ignore" },
);
let browser, page;
const observations = [];
try {
  for (let i = 0; ; i++) {
    try {
      if ((await fetch(url)).ok) break;
    } catch {
      /* Vite startup */
    }
    assert(i < 100, "Vite starts");
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  browser = await chromium.launch({ executablePath, headless: true });
  page = await browser.newPage({ viewport: { width: 1200, height: 1000 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem("FATE_LANGUAGE", "en"));
  await page.goto(url + "/test-results/sans/index.html");
  await page.getByRole("button", { name: "Enable audio", exact: true }).click();
  await page.locator('body[data-audio="ready"]').waitFor();
  await page.clock.install();
  await page.clock.pauseAt(new Date(Date.now() + 1000));
  const next = async () => {
    await page.getByRole("button", { name: "Next manual decision", exact: true }).click();
    await page.clock.runFor(32);
  };
  const syncSprites = () =>
    page.locator("[data-vfx-cue]").evaluateAll(async (elements) => {
      for (const el of elements) {
        for (const child of el.children) {
          const background = getComputedStyle(child).backgroundImage;
          if (background.startsWith("url(")) {
            const img = new Image();
            img.src = background.slice(5, -2);
            await img.decode();
          }
        }
        for (const animation of el.getAnimations({ subtree: true })) {
          const delay = getComputedStyle(animation.effect.target).animationDelay.split(",")[0];
          const delayMs = parseFloat(delay) * (delay.endsWith("ms") ? 1 : 1000);
          animation.pause();
          // Sample the same beam frame for orientation comparison. CSS has its
          // native clock; RAF, semantic offsets and audio keep the virtual clock.
          const elapsed =
            el.dataset.vfxEffect === "gasterBeam" ? 180 : Date.now() - Number(el.dataset.vfxStart);
          animation.currentTime = Math.max(0, elapsed + delayMs);
        }
      }
    });
  // Explicit attacker and defender decisions remain usable without waiting for art.
  await next();
  assert.equal(await page.locator('[data-vfx-effect="gasterCannon"]').count(), 0);
  const decisionCount = await page.evaluate(async () => {
    const fixtures = await (await fetch("./fixtures.json")).json();
    return fixtures.gaster.length - 1;
  });
  for (let i = 0; i < decisionCount; i++) {
    await next();
    await page.clock.runFor(750);
  }
  await page.clock.runFor(80);
  for (const player of ["P1", "P2"]) {
    assert.equal(
      await page.locator('[data-board="' + player + '"] [data-vfx-effect="gasterCannon"]').count(),
      1,
    );
    const beam = page.locator('[data-board="' + player + '"] [data-vfx-effect="gasterBeam"]');
    assert.equal(await beam.count(), 1);
    assert.equal(await beam.locator('[data-vfx-frames="20"]').count(), 2);
    const geometry = await beam.evaluate((el) => ({
      width: parseFloat(el.style.width),
      transform: el.style.transform,
      clipped: getComputedStyle(el.parentElement).overflow,
    }));
    assert(geometry.width > 250, "beam extends well beyond selected adjacent target");
    assert(geometry.transform.includes(player === "P1" ? "-45" : "135"));
    assert.equal(geometry.clipped, "hidden");
  }
  const beamStarts = await page
    .locator('[data-board="P1"] [data-vfx-effect="gasterBeam"]')
    .evaluate((el) => Number(el.dataset.vfxStart));
  await page.clock.runFor(Math.max(0, beamStarts - (await page.evaluate(() => Date.now())) + 180));
  await syncSprites();
  for (const player of ["P1", "P2"]) {
    assert(
      Number(
        await page
          .locator('[data-board="' + player + '"] [data-vfx-effect="gasterBeam"]')
          .evaluate((el) => getComputedStyle(el).opacity),
      ) > 0,
      "sampled beam is visible in both orientations",
    );
  }
  await page.screenshot({ path: path.join(output, "gaster-P1-P2.png"), fullPage: true });
  await page.clock.runFor(650);
  const gasterAudio = await page.evaluate(() => window.sansAudio);
  assert(
    gasterAudio.some((c) => c.key === "hero.sans.abilities.sansGasterBlaster.fire" && c.played),
    "fire asset decoded and Web Audio source started",
  );
  for (const key of ["charge", "fire"])
    assert.equal(
      gasterAudio.filter((c) => c.key === "hero.sans.abilities.sansGasterBlaster." + key).length,
      2,
      "one signature per recipient",
    );
  observations.push(
    "real manual Gaster chain: one cannon/charge/fire per recipient; paired animated board-edge diagonal, correct P1/P2 rotation; decisions usable during playback",
  );
  await page.clock.runFor(4000);
  const allyId = await page.evaluate(async () => {
    const fixtures = await (await fetch("./fixtures.json")).json();
    const final = fixtures.gaster.at(-1).P1;
    if (final.view.units[fixtures.allyId].hp !== 4 ||
        !final.batch.events.some((event) => event.type === "attackResolved" &&
          event.defenderId === fixtures.allyId && event.hit)) {
      throw new Error("Friendly target must have an authoritative hit and HP loss");
    }
    return fixtures.allyId;
  });
  assert.match(
    await page.locator('[data-board="P1"] [data-unit-id="' + allyId + '"] .board-outcome').innerText(),
    /4\//,
    "production board presents friendly damage once and ends at the authoritative HP",
  );
  observations.push("friendly target receives an authoritative hit and one HP loss; production owner board shows updated HP");
  await page.getByRole("button", { name: "Reconnect baseline", exact: true }).click();
  await page.clock.runFor(32);
  assert.equal(await page.locator("[data-vfx-cue]").count(), 0);
  assert.deepEqual(await page.evaluate(() => window.sansAudio), []);
  observations.push("completed Gaster reconnect baseline is silent");
  await page.getByRole("button", { name: "Last Attack baseline", exact: true }).click();
  await page.clock.runFor(32);
  await next();
  await page.clock.runFor(2500);
  assert.equal(await page.locator('[data-vfx-effect="unitDeath"]').count(), 0);
  const targetIndex = await page.evaluate(async () => {
    const f = await (await fetch("./fixtures.json")).json();
    return f.pending.P1.view.pendingRoll.context.legalTargetIds.indexOf(f.targetId);
  });
  assert.equal(await page.locator('[data-board="P1"] [data-pending-owner]').count(), 1);
  assert.equal(await page.locator('[data-board="P2"] [data-pending-owner]').count(), 0);
  assert.equal(
    await page.locator('[data-board="P2"] [data-testid="opponent-decision-status"]').count(),
    1,
  );
  await page.getByRole("button", { name: "Reconnect baseline", exact: true }).click();
  await page.clock.runFor(32);
  assert.deepEqual(await page.evaluate(() => window.sansAudio), []);
  await page.locator("[data-pending-owner] button").nth(targetIndex).click();
  await page.clock.runFor(32);
  await page.locator('[data-vfx-effect="sansCurseApply"]').first().waitFor({ state: "attached" });
  assert.equal(await page.locator('[data-vfx-effect="sansCurseApply"]').count(), 2);
  await page.clock.runFor(320);
  assert.equal(await page.locator('[data-vfx-effect="unitDeath"]').count(), 2);
  await page.screenshot({
    path: path.join(output, "curse-before-final-death.png"),
    fullPage: true,
  });
  await page.clock.runFor(800);
  const finalAudio = await page.evaluate(() => window.sansAudio);
  assert(
    finalAudio.some((c) => c.key === "hero.sans.abilities.sansLastAttack.apply" && c.played),
    "curse apply asset decoded and played",
  );
  assert.equal(finalAudio.filter((c) => c.key === "common.combat.death").length, 2);
  assert.equal(
    finalAudio.filter((c) => c.key === "hero.sans.abilities.sansLastAttack.apply").length,
    2,
  );
  observations.push(
    "real Last Attack pending state: Sans remains before final unitDied; production owner choice and opponent waiting; reconnect restores choice silently; accepted curse precedes one final death per recipient",
  );
  await page.getByRole("button", { name: "Reconnect baseline", exact: true }).click();
  await page.clock.runFor(32);
  await page.getByRole("button", { name: "Start cursed own turn", exact: true }).click();
  await page.clock.runFor(100);
  await page.locator('[data-vfx-effect="sansCurseTick"]').first().waitFor({ state: "attached" });
  assert.equal(await page.locator('[data-vfx-effect="sansCurseTick"]').count(), 2);
  await page.clock.runFor(300);
  assert.equal(await page.locator('[data-vfx-effect="sansCurseRemove"]').count(), 2);
  await page.clock.runFor(300);
  const tickAudio = await page.evaluate(() => window.sansAudio);
  assert(
    tickAudio.some((c) => c.key === "hero.sans.abilities.sansLastAttack.tick" && c.played),
    "curse tick asset decoded and played",
  );
  assert.equal(
    tickAudio.filter((c) => c.key === "hero.sans.abilities.sansLastAttack.tick").length,
    2,
  );
  assert.equal(
    tickAudio.filter((c) => c.key === "hero.sans.abilities.sansLastAttack.remove").length,
    2,
  );
  assert(!tickAudio.some((c) => c.key === "common.combat.death"));
  observations.push(
    "active curse reconnect is silent; next real own-turn 2-to-1 tick and removal each play once, no death",
  );
  assert.deepEqual(errors, []);
  const report = {
    observations,
    manualTwoPlayerGame: false,
    source: "real rules fixtures and production Board/pending components in headless Edge",
    audio: "scheduled keys, decoded assets and successful Web Audio starts verified; no subjective listening",
  };
  await writeFile(path.join(output, "report.json"), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} catch (error) {
  if (page) console.log("Audio observations:", await page.evaluate(() => window.sansAudio));
  if (page) await page.screenshot({ path: path.join(output, "failure.png"), fullPage: true });
  throw error;
} finally {
  await browser?.close();
  if (process.platform === "win32")
    spawnSync("taskkill", ["/pid", String(server.pid), "/T", "/F"], {
      windowsHide: true,
      stdio: "ignore",
    });
  else server.kill("SIGTERM");
}
